---
# tasks file for roles/ftpserver
- name: Install FTP package
  ansible.builtin.yum:
    name: vsftpd
    state: latest

- name: Start FTP Service
  ansible.builtin.service:
    name: vsftpd
    state: started
    enabled: yes

- name: Restart vsftpd
  ansible.builtin.service:
    name: vsftpd
    state: restarted
    enabled: yes
